/* Golden-oracle parity test: the TS lie layer vs the pinned Python mink.
 *
 * oracles/lie.json was generated by executing mink 1.2.0 (pinned commit
 * 44c8a6ab66d27d06249f9018334a51662605e3e4, with its C lie-ops extension
 * active) under mujoco 3.10.0 / numpy 2.5.1 — see the file's provenance
 * object. Every value is full-precision float64; the generation is
 * byte-deterministic (verified across two runs). The TS port must reproduce
 * the reference within ATOL on log, jlog, adjoint, and rminus.
 */
import { describe, expect, it } from 'vitest';

import { SE3, SO3 } from './lie';
import lieOracle from './oracles/lie.json';

const MINK_COMMIT = '44c8a6ab66d27d06249f9018334a51662605e3e4';
const ATOL = 1e-9;

function se3FromParams(wxyzXyz: readonly number[]): SE3 {
  return SE3.fromRotationTranslation(SO3.fromQuatWxyz(wxyzXyz.slice(0, 4)), wxyzXyz.slice(4));
}

function expectClose(actual: Float64Array, expected: readonly number[], label: string): void {
  expect(actual.length, `${label}: length`).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(
      Math.abs((actual[i] ?? NaN) - (expected[i] ?? NaN)),
      `${label}[${i}]`,
    ).toBeLessThanOrEqual(ATOL);
  }
}

describe('lie golden oracles (python mink parity)', () => {
  it('fixture provenance pins the mink commit this port derives from', () => {
    expect(lieOracle.provenance.mink_commit).toBe(MINK_COMMIT);
    expect(lieOracle.provenance.mujoco_version).toBe('3.10.0');
    expect(lieOracle.elements.length).toBe(10);
    expect(lieOracle.pairs.length).toBe(5);
  });

  it('SE3.log matches mink on all sampled elements', () => {
    for (const [i, el] of lieOracle.elements.entries()) {
      expectClose(SE3.log(se3FromParams(el.wxyz_xyz)), el.log, `element ${i} log`);
    }
  });

  it('SE3.jlog matches mink on all sampled elements', () => {
    for (const [i, el] of lieOracle.elements.entries()) {
      expectClose(SE3.jlog(se3FromParams(el.wxyz_xyz)), el.jlog.flat(), `element ${i} jlog`);
    }
  });

  it('SE3.adjoint matches mink on all sampled elements', () => {
    for (const [i, el] of lieOracle.elements.entries()) {
      expectClose(
        SE3.adjoint(se3FromParams(el.wxyz_xyz)),
        el.adjoint.flat(),
        `element ${i} adjoint`,
      );
    }
  });

  it('SE3.rminus matches mink on all sampled pairs', () => {
    for (const [i, pair] of lieOracle.pairs.entries()) {
      const x = se3FromParams(pair.X_wxyz_xyz);
      const y = se3FromParams(pair.Y_wxyz_xyz);
      // Oracle records Y.rminus(X) = (X⁻¹ ∘ Y).log(); ours is rminus(a, b) = log(b⁻¹ ∘ a).
      expectClose(SE3.rminus(y, x), pair.rminus, `pair ${i} rminus`);
    }
  });
});
