/* Golden-oracle parity test: the full TS differential-IK pipeline vs the
 * pinned Python mink, on THIS project's humanoid and shipped library poses.
 *
 * oracles/ik_steps.json and oracles/com_support.json were generated by
 * executing mink 1.2.0 (pinned 44c8a6ab66d27d06249f9018334a51662605e3e4)
 * + mujoco 3.10.0 on apps/web/src/spike/scene.xml with four library poses;
 * for each, every intermediate is recorded at full float64 precision: task
 * errors and jacobians, the assembled QP (H, c, G, h — exactly what daqp
 * received via mink.build_ik), the daqp solution v, and the integrated
 * q_next. Generation is byte-deterministic (verified across two runs).
 *
 * The TS port must reproduce the pipeline end to end: errors/jacobians to
 * 1e-9/1e-8, the QP to 1e-8, and the solved step (a different QP solver —
 * Goldfarb–Idnani here vs daqp there — on the same strictly convex problem)
 * to V_ATOL.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import sceneXml from '../spike/scene.xml?raw';
import { GateConfiguration } from './configuration';
import { loadGateEngine } from './engine';
import { SE3, SO3 } from './lie';
import { ConfigurationLimit } from './limits';
import { ComTask, FrameTask, PostureTask, type Task } from './tasks';
import { buildIk, solveIk } from './solve';
import comSupport from './oracles/com_support.json';
import ik from './oracles/ik_steps.json';

const MINK_COMMIT = '44c8a6ab66d27d06249f9018334a51662605e3e4';

const ERR_ATOL = 1e-9; // task errors
const JAC_ATOL = 1e-8; // task jacobians
const QP_ATOL = 1e-8; // assembled H, c, G, h
const V_ATOL = 1e-6; // daqp vs Goldfarb–Idnani on the same strictly convex QP
const QNEXT_ATOL = 1e-8; // integrated next configuration (v error × dt)

type Engine = Awaited<ReturnType<typeof loadGateEngine>>;

function se3FromParams(wxyzXyz: readonly number[]): SE3 {
  return SE3.fromRotationTranslation(SO3.fromQuatWxyz(wxyzXyz.slice(0, 4)), wxyzXyz.slice(4));
}

function maxAbsDiff(actual: ArrayLike<number>, expected: readonly number[]): number {
  expect(actual.length).toBe(expected.length);
  let worst = 0;
  for (let i = 0; i < expected.length; i++) {
    worst = Math.max(worst, Math.abs((actual[i] ?? NaN) - (expected[i] ?? NaN)));
  }
  return worst;
}

/** Build the oracle's task trio + limit at a case's configuration. */
function buildCase(engine: Engine, kase: (typeof ik.cases)[number]) {
  const configuration = new GateConfiguration(engine, Float64Array.from(kase.qpos));
  const frame = new FrameTask('geom', configuration.geomId('hand_right'), 1.0, 0.5);
  frame.setTarget(se3FromParams(kase.frame_target_wxyz_xyz));
  const posture = new PostureTask(configuration, 0.01);
  posture.setTarget(kase.qpos);
  const com = new ComTask(1.0);
  com.setTarget(kase.com_target);
  const limit = new ConfigurationLimit(configuration, 0.95);
  const tasks: Task[] = [frame, posture, com];
  return { configuration, frame, posture, com, limit, tasks };
}

describe('ik golden oracles (python mink parity, this humanoid, library poses)', () => {
  let engine: Engine;

  beforeAll(async () => {
    engine = await loadGateEngine(sceneXml);
  }, 30000);

  afterAll(() => {
    engine.dispose();
  });

  it('fixture provenance pins the mink commit and this scene', () => {
    expect(ik.provenance.mink_commit).toBe(MINK_COMMIT);
    expect(ik.nq).toBe(35);
    expect(ik.nv).toBe(33);
    expect(ik.solver).toBe('daqp');
    expect(ik.cases.length).toBe(4);
  });

  for (const [ci, kase] of ik.cases.entries()) {
    describe(`case ${kase.pose_id}`, () => {
      it('reproduces the hand_right world transform', () => {
        const { configuration } = buildCase(engine, kase);
        const t = configuration.getFrameTransform('geom', configuration.geomId('hand_right'));
        const want = kase.hand_right_transform_world_wxyz_xyz;
        // Quaternion double cover: compare against ±q.
        const direct = maxAbsDiff(t.wxyzXyz, want);
        const flipped = maxAbsDiff(
          t.wxyzXyz,
          want.map((x, i) => (i < 4 ? -x : x)),
        );
        expect(Math.min(direct, flipped)).toBeLessThanOrEqual(ERR_ATOL);
      });

      it('reproduces task errors and jacobians', () => {
        const { configuration, frame, posture, com } = buildCase(engine, kase);
        expect(
          maxAbsDiff(frame.computeError(configuration), kase.tasks.frame.error),
        ).toBeLessThanOrEqual(ERR_ATOL);
        expect(
          maxAbsDiff(frame.computeJacobian(configuration), kase.tasks.frame.jacobian.flat()),
        ).toBeLessThanOrEqual(JAC_ATOL);
        expect(
          maxAbsDiff(posture.computeError(configuration), kase.tasks.posture.error),
        ).toBeLessThanOrEqual(ERR_ATOL);
        expect(
          maxAbsDiff(posture.computeJacobian(configuration), kase.tasks.posture.jacobian.flat()),
        ).toBeLessThanOrEqual(JAC_ATOL);
        expect(
          maxAbsDiff(com.computeError(configuration), kase.tasks.com.error),
        ).toBeLessThanOrEqual(ERR_ATOL);
        expect(
          maxAbsDiff(com.computeJacobian(configuration), kase.tasks.com.jacobian.flat()),
        ).toBeLessThanOrEqual(JAC_ATOL);
      });

      it('assembles the same QP mink handed to daqp (H, c, G, h)', () => {
        const { configuration, tasks, limit } = buildCase(engine, kase);
        const qp = buildIk(configuration, tasks, ik.dt, ik.damping, [limit]);
        expect(maxAbsDiff(qp.H, kase.qp.H.flat())).toBeLessThanOrEqual(QP_ATOL);
        expect(maxAbsDiff(qp.c, kase.qp.c)).toBeLessThanOrEqual(QP_ATOL);
        expect(qp.m).toBe(kase.qp.h.length);
        expect(qp.G).not.toBeNull();
        expect(qp.h).not.toBeNull();
        expect(maxAbsDiff(qp.G!, kase.qp.G.flat())).toBeLessThanOrEqual(QP_ATOL);
        expect(maxAbsDiff(qp.h!, kase.qp.h)).toBeLessThanOrEqual(QP_ATOL);
      });

      it('solves to the same step (v) and integrates to the same q_next', () => {
        const { configuration, tasks, limit } = buildCase(engine, kase);
        const result = solveIk(configuration, tasks, ik.dt, ik.damping, [limit]);
        expect(result.found).toBe(true);
        expect(maxAbsDiff(result.v, kase.v)).toBeLessThanOrEqual(V_ATOL);
        expect(
          maxAbsDiff(configuration.integrate(result.v, ik.dt), kase.q_next),
        ).toBeLessThanOrEqual(QNEXT_ATOL);
      });

      it('agrees on both subtree COM conventions (world row 0 vs humanoid row 1)', () => {
        const { configuration } = buildCase(engine, kase);
        const oracleCase = comSupport.cases[ci]!;
        expect(oracleCase.pose_id).toBe(kase.pose_id);
        expect(
          maxAbsDiff(configuration.subtreeCom(1), oracleCase.subtree_com_1),
        ).toBeLessThanOrEqual(ERR_ATOL);
        // World-body subtree COM (includes the ball) — what check.ts uses.
        const worldCom = engine.data.subtree_com as Float64Array;
        expect(
          maxAbsDiff([worldCom[0]!, worldCom[1]!, worldCom[2]!], oracleCase.subtree_com_0),
        ).toBeLessThanOrEqual(ERR_ATOL);
      });
    });
  }

  it('reproduces the LM-damping variant (stance-clean, frame lmDamping 1e-3)', () => {
    const kase = ik.cases[0]!;
    const lmv = kase.lm_damping_variant!;
    const configuration = new GateConfiguration(engine, Float64Array.from(kase.qpos));
    const frame = new FrameTask(
      'geom',
      configuration.geomId('hand_right'),
      1.0,
      0.5,
      1,
      lmv.frame_lm_damping,
    );
    frame.setTarget(se3FromParams(kase.frame_target_wxyz_xyz));
    const posture = new PostureTask(configuration, 0.01);
    posture.setTarget(kase.qpos);
    const com = new ComTask(1.0);
    com.setTarget(kase.com_target);
    const limit = new ConfigurationLimit(configuration, 0.95);
    const tasks: Task[] = [frame, posture, com];
    const qp = buildIk(configuration, tasks, ik.dt, ik.damping, [limit]);
    expect(maxAbsDiff(qp.H, lmv.H.flat())).toBeLessThanOrEqual(QP_ATOL);
    const result = solveIk(configuration, tasks, ik.dt, ik.damping, [limit]);
    expect(result.found).toBe(true);
    expect(maxAbsDiff(result.v, lmv.v)).toBeLessThanOrEqual(V_ATOL);
  });
});
